# Generated by Django 4.2.12 on 2024-08-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_cartdb_delete_servicepackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='Productname',
            new_name='Servicename',
        ),
    ]
