# Generated by Django 4.2.12 on 2024-08-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_rename_productname_cartdb_servicename'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('EmailAddress', models.EmailField(blank=True, max_length=100, null=True)),
                ('Total', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
